### Input
# input rgba image path (default to None, can be load in GUI too)
input:
# input text prompt (default to None, can be input in GUI too)
prompt: "Darth Vader, full body, 3d asset, without cloak,"
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image
elevation: 0
# reference image resolution
ref_size: 256
# density thresh for mesh extraction
density_thresh: 1

pose_name:
# 3d keypoints path for sdcn_depth, pkl file
keypoints_path: frankmocap/output/0999/openpose.pkl
# 3d mesh path for sdcn_depth, obj file
mesh_path: frankmocap/output/0999/mesh.obj

### Output
outdir: logs
mesh_format: obj
save_path: darthvader_999
save_interval: 500

#stable diffution
load_from_local: True
local_path: ./pretrained_models/DarthVader.ckpt

### Training
# guidance loss weights (0 to disable)
lambda_sd: 1
mvdream: False
sdcn: False
sdcn_depth: True
lambda_zero123: 0
# training batch size per iter
batch_size: 1
# training iterations for stage 1
iters: 7000
# training iterations for stage 2
iters_refine: 50
# training camera radius
radius: 3.1
# training camera fovy
fovy: 49.1
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.2

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

# training
guidance_scale: 7.5

### Gaussian splatting
num_pts: 5000
sh_degree: 0
position_lr_init: 0.005
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 1000
feature_lr: 0.005
opacity_lr: 0.005
scaling_lr: 0.003
rotation_lr: 0.003
percent_dense: 0.01
density_start_iter: 0
density_end_iter: 3500
densification_interval: 350
opacity_reset_interval: 1751
densify_grad_threshold: 0.01

min_opacity: 0.01
extent: 2.5
max_screen_size: 0.5

#open this when the character gets out of the screen
dynamic_radius: False
### Loggingz
wandb: True
### Misc
debug: False
